# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: horizon_dongle_display dongle_display
    artifact-name: horizon_dongle_display

  - board: nice_nano_v2
    shield: horizon
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: horizon

  - board: nice_nano_v2
    shield: horizon_peripheral_left
    cmake-args: -DCONFIG_ZMK_SPLIT=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: horizon_peripheral_left

  - board: nice_nano_v2
    shield: settings_reset

